image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test


job-build:
    stage: build
    before_script:
      - apt update -y
      - apt upgrade -y
      - apt install cmake -y
    script:
        - mkdir "$CI_PROJECT_DIR/build/"
        - cd "$CI_PROJECT_DIR/build/"
        - cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" ..
        - cd "$CI_PROJECT_DIR/build/"
        - make
    artifacts:
        paths:
            - build/core/phoenix-core-tests


job-test:
    stage: test
    script:
        - cd "$CI_PROJECT_DIR/core/tests/"
        - $CI_PROJECT_DIR/build/core/phoenix-core-tests ~[proprietary] -r junit -o report.xml
    needs:
        - job-build
    artifacts:
        when: always
        reports:
            junit: report.xml